# workflow follows: https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: what to bump?
        required: true
        options:
          - patch
          - minor
          - major


jobs:
  bump:

    name: Bump Version and Tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: bump-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "action@github.com"

          if [ "${{ github.event.inputs.bump }}" = "major" ]; then
            uv run --frozen bumpver update --major
          elif [ "${{ github.event.inputs.bump }}" = "minor" ]; then
            uv run --frozen bumpver update --minor 
          # check if the current version is a release candidate
          elif [[ "${{ github.event.inputs.bump }}" = "patch" ]]; then
              uv run --frozen bumpver update --patch
          fi
